package com.mctng.lifemc2;

import com.mctng.lifemc2.api.API;
import com.mctng.lifemc2.commands.Commands;
import com.mctng.lifemc2.config.ConfigHandler;
import com.mctng.lifemc2.config.ConfigWrapper;
import com.mctng.lifemc2.datahandler.DataHandler;
import com.mctng.lifemc2.listeners.InteractListener;
import com.mctng.lifemc2.listeners.LoginListener;
import com.mctng.lifemc2.listeners.PlayerRespawnListener;
import com.mctng.lifemc2.vault.VaultHandler;

import org.bukkit.plugin.java.JavaPlugin;

//Main plugin class
public class LifeMc2 extends JavaPlugin {

	private ConfigHandler configHandler = new ConfigHandler(this);
	private VaultHandler vaultHandler = new VaultHandler(this);
	private DataHandler dataHandler;
	
	private API api = new API(this);

	private ConfigWrapper dataConfig = new ConfigWrapper(this, "", "data.yml");
	private ConfigWrapper langConfig = new ConfigWrapper(this, "",
			"messages.yml");

	public void onDisable() {
		
		dataConfig.saveConfig();
		
		getLogger().info(
				"LifeMc2 v" + getDescription().getVersion()
						+ " has been disabled!");
	}

	public void onEnable() {

		// Load config from jar.
		configHandler.loadMainConfig();

		// Load data.yml
		dataConfig.createNewFile("Loaded data.yml",
				"Do not edit this file manually.");

		// Load messages.yml
		langConfig
				.createNewFile("Loaded messages.yml",
						"You can edit all messages to your liking. \nColour codes are supported.");
	
		configHandler.loadLangConfig();
		
		// Load data handler
		dataHandler = new DataHandler(this);

		this.getCommand("lifemc").setExecutor(new Commands(this));

		registerListeners();

		// Load Vault
		vaultHandler.loadVault();

		getLogger().info(
				"LifeMc2 v" + getDescription().getVersion()
						+ " has been enabled!");

	}

	private void registerListeners() {
		getServer().getPluginManager().registerEvents(
				new InteractListener(this), this);
		getServer().getPluginManager().registerEvents(
				new PlayerRespawnListener(this), this);
		getServer().getPluginManager().registerEvents(new LoginListener(this),
				this);
	}

	public ConfigHandler getConfigHandler() {
		return configHandler;
	}

	public ConfigWrapper getDataConfig() {
		return dataConfig;
	}
	
	public ConfigWrapper getLangConfig() {
		return langConfig;
	}

	public DataHandler getDataHandler() {
		return dataHandler;
	}
	
	public VaultHandler getVaultHandler() {
		return vaultHandler;
	}
	
	public API getAPI() {
		return api;
	}
}